### PR TITLE
Add monitor to Router model

### PR DESCRIPTION
**Pull request by miyukki**
# Purpose
fog-sakuracloud cannot get the network bandwidth statistics of router.

# Changes
- Implement `Fog::Network::SakuraCloud::Router#monitor` method.
http://developer.sakura.ad.jp/cloud/api/1.1/internet/#get_internet_internetid_monitor

Any thoughts?

### CODE REVIEW

**Comment by sawanoboly** [comment]
Thanks :smiley: 

Can you change name of request ?
`monitor_router ` feels a little strange to me. e.g. retrieve_monitor, or collect_monitor.

**Comment by miyukki** [comment]
@sawanoboly 
That's a cool answer!
I suggest the method name `list_router_traffics` instead of `monitor_router`.
Or would you like `collect_monitor`?

**Comment by sawanoboly** [comment]
@miyukki 
hmm, collect_monitor is better.
Certainly can be provided value is the total traffic amount, but since the name of the API is monitor.

**Comment by miyukki** [comment]
@sawanoboly 
There are APIs that monitor the appliance network bandwidth other than router on SakuraCloud API 
http://developer.sakura.ad.jp/cloud/api/1.1/appliance/#get_appliance_applianceid_interface_index_monitor

I think the name `collect_monitor` is conflicting when implement its api.
Thoughts?

**Comment by sawanoboly** [comment]
@miyukki Ah.. you are correct. It'll not maybe conflict but will confuse users.
Probably I'll create new model when add appliances as loadbarancer or create new name by them's role.

Well then, let's use `connect_monitor_router` to this request and use `connect_monitor` in route model.

**Comment by miyukki** [comment]
> Well then, let's use connect_monitor_router to this request and use connect_monitor in route model.

@sawanoboly Did you mean `collect` right?
I rebased and force pushed this request. Please review it.

**Comment by sawanoboly** [comment]
LGTM. Thanks :+1:

**Comment by sawanoboly** [comment]
released as v1.5.1.

**Comment by sawanoboly** [comment]
F.Y.I @miyukki 

Because I noticed that the filter can be used a little while ago, I've add it. https://github.com/fog/fog-sakuracloud/commit/f9e7b0ef8208d0aaee1cee3cd185586c5ccb1f9d

**Comment by miyukki** [comment]
@sawanoboly That's so good idea. Thank you. :+1:

**Pull request merged**
