### PR TITLE
Implement Router#change_router_bandwidth

### PR DESCRIPTION
**Pull request by miyukki**
# Purpose
Implement Router#change_router_bandwidth.

# Changes
- Implement `Fog::Network::SakuraCloud::Router#change_router_bandwidth` method.
http://developer.sakura.ad.jp/cloud/api/1.1/internet/#put_internet_internetid_bandwidth

Any thoughts?

### CODE REVIEW

**Comment by sawanoboly** [comment]
Thanks! I've tested.It works.

But I've noticed that there is inconsistent behavior between create router with get router.

- create action returns id of switch.
- get action returns id of internet(router).

The change_router_bandwidth requires id of "Internet"

success example:
```
> router = network.routers.first
> router.change_bandwidth(1000)
=> true
```

failure example:
```
> router = network.routers.create(:name => 'foort02', :networkmasklen => 28)
> router.id
=> "112701092840"
> router.change_bandwidth(1000)
[fog][WARNING] 対象が見つかりません。対象は利用できない状態か、IDまたはパスに誤りがあります。
```

Once, I merge this PR. And then, I'll try to resolve inconsistent before release this feature. please wait.

**Comment by sawanoboly** [comment]
release as v1.7.0. Thanks!

**Comment by sawanoboly** [comment]
@miyukki 

F.Y.I. I've changed behavior to update router instance by new one.
https://github.com/fog/fog-sakuracloud/commit/e821b60a62094623d24fd84c3857dd7a28bfda15

**Comment by miyukki** [comment]
@sawanoboly Thanks :+1:

**Pull request merged**
